[project]
name = "fft-vis"
version = "0.1.0"
description = " A small visualization of the 2D FFT of images. "
readme = "README.md"
requires-python = ">=3.11.7"
dependencies = [
    "flask>=3.1.1",
    "matplotlib>=3.10.5",
    "numpy>=2.3.2",
    "pillow>=11.3.0",
]
